=== JamesGPerks/wsdAssignment1/users.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://wsd.com/assignment2"
	xmlns="http://wsd.com/assignment2"
	elementFormDefault="qualified">

	<!-- Type Declarations -->
	<xs:simpleType name="password">
		<xs:restriction base="xs:string">
			<xs:minLength value="8" />
			<xs:maxLength value="20" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Element Declarations -->

	<xs:element name="pollcreators">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="creator" maxOccurs="unbounded"
					minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="username" />
							<xs:element type="password" name="password" />
						</xs:sequence>
						<xs:attribute type="xs:integer" name="id" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== JamesGPerks/wsdAssignment1/WebContent/WEB-INF/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<pollcreators xmlns="http://wsd.com/assignment2" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://wsd.com/assignment2 users.xsd">
	
	<creator id="0">
		<username>John</username>
		<password>12345678</password>
	</creator>
	<creator id="1">
		<username>Brodie</username>
		<password>hello123</password>
	</creator>
	<creator id="2">
		<username>Zoe</username>
		<password>d0gsArecoo1</password>
	</creator>
	<creator id="3">
		<username>Tiarne</username>
		<password>CakesAreTasty</password>
	</creator>
</pollcreators>
